In [46]:
import seaborn as sns
import pandas as pd
import matplotlib.style as style
import matplotlib.pyplot as plt

In [31]:
style.use('seaborn-poster')
style.use('fivethirtyeight')

## Merchandise trade

### Total exports by main commodity group, % (2016)

In [34]:
df = pd.DataFrame([{"Main Commodity Group": "Agricultural products", "Total exports": 11.1},
                   {"Main Commodity Group": "Fuels and mining products", "Total exports": 8.7},
                   {"Main Commodity Group": "Manufactures", "Total exports": 74.9},
                  {"Main Commodity Group": "Other", "Total exports": 5.2}])
df

        Main Commodity Group  Total exports
0      Agricultural products           11.1
1  Fuels and mining products            8.7
2               Manufactures           74.9
3                      Other            5.2

### Total exports by main destination, % (2017)

In [57]:
df = pd.DataFrame([{"Destination": "EU", "Total exports": 18.3},
                  {"Destination": "Mexico", "Total exports": 15.7},
                  {"Destination": "Japan", "Total exports": 4.4},
                  {"Destination": "Canada", "Total exports": 18.3},
                  {"Destination": "China", "Total exports": 8.4},
                  {"Destination": "Other", "Total exports": 34.9}])
df

  Destination  Total exports
0          EU           18.3
1      Mexico           15.7
2       Japan            4.4
3      Canada           18.3
4       China            8.4
5       Other           34.9

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from trade_policy_analysis import client

In [3]:
oec = client.OEC(classification="HS07")

In [132]:
oec.countries.columns

Index(['borders_land', 'borders_maritime', 'color', 'comtrade_name',
       'display_id', 'icon', 'id', 'id_2char', 'id_num', 'image',
       'image_author', 'image_link', 'name', 'palette', 'weight'],
      dtype='object')

In [133]:
oec.get_country_image("tun")

'https://flic.kr/p/94asmu'

In [5]:
usa_exports_17 = oec.get_exports(origin="usa", year=2017, product="show", destination="all")

https://atlas.media.mit.edu/hs07/export/2017/usa/all/show/

In [6]:
usa_exports_17

,export_rca,export_val,hs07_id,import_rca,import_val,origin_id,year,hs07_section,hs07_chapter,hs07_heading,hs07_subheading
1,1.721,2.005696e+08,01010110,0.613,1.186011e+08,nausa,2017.0,01,01,01,10
2,1.650,1.715735e+08,01010190,1.981,3.418832e+08,nausa,2017.0,01,01,01,90
4,0.612,6.217346e+07,01010210,0.025,4.212070e+06,nausa,2017.0,01,01,02,10
5,0.313,1.670099e+08,01010290,1.791,1.587794e+09,nausa,2017.0,01,01,02,90
7,1.322,1.855740e+07,01010310,0.004,9.431000e+04,nausa,2017.0,01,01,03,10
8,0.015,2.303985e+06,01010391,0.802,1.987547e+08,nausa,2017.0,01,01,03,91
9,0.026,4.363537e+06,01010392,0.505,1.426864e+08,nausa,2017.0,01,01,03,92
11,0.015,1.802487e+06,01010410,0.002,3.226254e+05,nausa,2017.0,01,01,04,10
12,0.017,2.519707e+05,01010420,0.007,1.777566e+05,nausa,2017.0,01,01,04,20
14,1.910,1.882803e+08,01010511,0.044,7.249335e+06,nausa,2017.0,01,01,05,11
15,1.171,1.317576e+07,01010512,1.236,2.307339e+07,nausa,2017.0,01,01,05,12
16,0.263,8.267864e+05,01010519,0.697,3.634553e+06,nausa,2017.0,01,01,05,19
17,0.039,3.862618e+06,01010594,0.009,1.399936e+06,nausa,2017.0,01,01,05,94
18,0.045,8.780508e+05,01010599,0.282,9.042444e+06,nausa,2017.0,01,01,05,99
20,0.348,3.554758e+06,01010611,3.061,5.195214e+07,nausa,2017.0,01,01,06,11
21,0.061,7.241128e+04,01010612,0.072,1.400000e+05,nausa,2017.0,01,01,06,12
22,1.144,5.898137e+07,01010619,0.366,3.132398e+07,nausa,2017.0,01,01,06,19
23,2.194,8.930391e+06,01010620,1.430,9.660934e+06,nausa,2017.0,01,01,06,20
24,1.350,3.093910e+06,01010631,0.024,9.227533e+04,nausa,2017.0,01,01,06,31
25,0.242,4.713897e+05,01010632,0.044,1.406827e+05,nausa,2017.0,01,01,06,32
26,0.395,1.719344e+06,01010639,0.159,1.152513e+06,nausa,2017.0,01,01,06,39
27,0.273,8.683717e+06,01010690,1.604,8.481575e+07,nausa,2017.0,01,01,06,90
29,0.054,8.238991e+06,01020110,0.101,2.580210e+07,nausa,2017.0,01,02,01,10
30,0.667,2.282820e+08,01020120,0.896,5.089237e+08,nausa,2017.0,01,02,01,20
31,2.461,3.006438e+09,01020130,1.115,2.261400e+09,nausa,2017.0,01,02,01,30
33,0.245,2.142189e+06,01020210,0.008,1.099916e+05,nausa,2017.0,01,02,02,10
34,5.028,6.994095e+08,01020220,0.147,3.385997e+07,nausa,2017.0,01,02,02,20
35,1.210,1.942036e+09,01020230,0.828,2.204840e+09,nausa,2017.0,01,02,02,30
37,0.049,9.186603e+06,01020311,0.051,1.578196e+07,nausa,2017.0,01,02,03,11
38,2.845,9.151119e+08,01020312,0.325,1.736940e+08,nausa,2017.0,01,02,03,12
...,...,...,...,...,...,...,...,...,...,...,...
6188,0.153,1.616028e+06,20960850,0.469,8.204736e+06,nausa,2017.0,20,96,08,50
6189,0.113,1.643040e+06,20960860,0.641,1.549966e+07,nausa,2017.0,20,96,08,60
6190,0.207,2.126159e+06,20960891,0.853,1.454418e+07,nausa,2017.0,20,96,08,91
6191,0.761,2.281865e+07,20960899,1.061,5.282786e+07,nausa,2017.0,20,96,08,99
6193,0.097,8.869037e+06,20960910,1.633,2.478595e+08,nausa,2017.0,20,96,09,10
6194,0.091,6.223273e+05,20960920,0.016,1.842760e+05,nausa,2017.0,20,96,09,20
6195,0.355,9.765815e+06,20960990,2.139,9.771045e+07,nausa,2017.0,20,96,09,90
6197,0.098,4.441764e+06,20961000,1.901,1.436603e+08,nausa,2017.0,20,96,10,00
6199,0.626,1.457659e+07,20961100,1.375,5.315719e+07,nausa,2017.0,20,96,11,00
6201,1.706,2.044295e+08,20961210,0.253,5.028630e+07,nausa,2017.0,20,96,12,10
6202,1.372,6.713329e+06,20961220,1.254,1.018478e+07,nausa,2017.0,20,96,12,20
6204,0.227,1.241447e+07,20961310,1.675,1.523356e+08,nausa,2017.0,20,96,13,10
6205,0.143,3.847893e+06,20961320,0.429,1.912228e+07,nausa,2017.0,20,96,13,20
6206,2.159,7.146556e+07,20961380,1.686,9.265726e+07,nausa,2017.0,20,96,13,80
6207,0.519,9.517552e+06,20961390,0.846,2.573636e+07,nausa,2017.0,20,96,13,90
6209,0.077,1.557740e+06,20961400,0.766,2.582821e+07,nausa,2017.0,20,96,14,00
6211,0.081,3.211656e+06,20961511,0.001,7.002600e+04,nausa,2017.0,20,96,15,11
6212,0.088,3.299220e+06,20961519,1.382,8.639823e+07,nausa,2017.0,20,96,15,19
6213,0.105,2.595228e+06,20961590,1.624,6.674764e+07,nausa,2017.0,20,96,15,90
6215,0.553,4.389541e+07,20961610,1.042,1.372779e+08,nausa,2017.0,20,96,16,10
6216,1.005,2.920839e+07,20961620,1.067,5.148663e+07,nausa,2017.0,20,96,16,20
6218,0.144,2.417125e+07,20961700,1.699,4.724118e+08,nausa,2017.0,20,96,17,00
6220,0.217,9.924738e+06,20961800,1.145,8.703489e+07,nausa,2017.0,20,96,18,00
6222,2.718,2.809759e+09,21970110,3.304,5.671775e+09,nausa,2017.0,21,97,01,10
6223,4.056,6.874112e+07,21970190,0.004,1.183950e+05,nausa,2017.0,21,97,01,90
6225,4.131,1.111173e+08,21970200,2.935,1.310967e+08,nausa,2017.0,21,97,02,00
6227,3.165,7.550999e+08,21970300,2.650,1.049784e+09,nausa,2017.0,21,97,03,00
6229,0.889,5.861120e+06,21970400,0.002,2.221300e+04,nausa,2017.0,21,97,04,00
6231,2.310,1.586819e+08,21970500,1.886,2.150785e+08,nausa,2017.0,21,97,05,00
6233,3.843,3.780092e+08,21970600,0.001,8.822500e+04,nausa,2017.0,21,97,06,00